# Generated by Django 6.0.3 on 2026-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrolerule',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='accessrolerule',
            name='can_write',
        ),
        migrations.AddField(
            model_name='accessrolerule',
            name='create_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrolerule',
            name='delete_all_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrolerule',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrolerule',
            name='read_all_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrolerule',
            name='read_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrolerule',
            name='update_permission',
            field=models.BooleanField(default=False),
        ),
    ]
