# Generated by Django 6.0.3 on 2026-03-10 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_accessrolerule_update_all_permission_user_jwt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesselement',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='businesselement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='permissions.businesselement'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_elements', to='permissions.user'),
        ),
    ]
